AWSTemplateFormatVersion: '2010-09-09'
Description: This Template creates an Ec2 instance with user data and imports values from template A.

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.medium
      - t3.micro
      - m1.small
      - m1.large
      - m3.medium
      - m3.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m5.large
  DepartmentName:
      Description: Department name for the EC2 instance
      Type: String
  AreaManager:
      Description: Area manager for the EC2 instance
      Type: String

  DBPwd:
    NoEcho: true
    Description: DB admin password
    Type: String
    MinLength: 1
    MaxLength: 41
    AllowedPattern: '^[a-zA-Z0-9]*$'

Mappings:
  RegionAmiMap:
    us-east-1:
      HVM64: ami-0c02fb55956c7d316
    us-east-2:
      HVM64: ami-060a84cbcb5c14844
    us-west-2:
      HVM64: ami-08962a4068733a2b6
    eu-west-1:
      HVM64: ami-052efd3df9dad4825

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [RegionAmiMap, !Ref "AWS::Region", HVM64]
      SubnetId: !ImportValue SampleNetworkCrossStack-SubnetID
      SecurityGroupIds:
        - !ImportValue SampleNetworkCrossStack-SecurityGroupID
      UserData:
          Fn::Base64: !Sub |
             #!/bin/bash
             yum update -y
             yum install httpd -y
             systemctl start httpd
             systemctl enable httpd
             echo "Welcome to our first user data launch throught CloudFormation" > /var/www/html/index.html
      Tags:
        - Key: Name
          Value: My-Yaml-Ec2instance
        - Key: PatrickDBPwd
          Value: !Ref DBPwd
  myEIP:
      Type: AWS::EC2::EIP
      Properties:
        InstanceId: !Ref EC2Instance

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref EC2Instance

  PrivateIp:
    Description: This returns the private IP of the EC2 instance
    Value: !GetAtt EC2Instance.PrivateIp

  PublicDnsName:
    Description: This returns the public DNS name of the EC2 instance
    Value: !GetAtt EC2Instance.PublicDnsName

  Departmentsub: 
    Description: This sub is a variable within a given string
    Value: !Sub "The department that the EC2 belongs to is ${DepartmentName}"

  AreaManagersub: 
    Description: This sub is a variable within a given string
    Value: !Sub "The Area Manager of the EC2 is ${AreaManager}"